name: Generate docs

on:
  push:
    branches:
      - "main"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: |
          git fetch origin main
          git checkout main
      - name: Installing dependencies
        run: yarn install
      - name: Generating docs
        run: yarn docs
      - name: Force add docs
        run: git add docs -f
      - name: Configuring user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Commit and push
        run: |
          git commit -m "docs: from ${{ github.sha }}" || true
           git push origin ${{ github.ref }} || true
